"""Add sequence_number to messages and create tool_call_logs table

Revision ID: 78c5de432ae1
Revises: f00ef5a9ad43
Create Date: 2026-02-04 01:56:44.861631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78c5de432ae1'
down_revision: Union[str, Sequence[str], None] = 'f00ef5a9ad43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=50), nullable=False),
    sa.Column('arguments', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'ERROR', name='toolcallstatus'), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_call_logs_conversation_id'), 'tool_call_logs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_tool_call_logs_created_at'), 'tool_call_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_tool_call_logs_tool_name'), 'tool_call_logs', ['tool_name'], unique=False)
    op.create_index(op.f('ix_tool_call_logs_user_id'), 'tool_call_logs', ['user_id'], unique=False)
    op.add_column('messages', sa.Column('sequence_number', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_messages_sequence_number'), 'messages', ['sequence_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_sequence_number'), table_name='messages')
    op.drop_column('messages', 'sequence_number')
    op.drop_index(op.f('ix_tool_call_logs_user_id'), table_name='tool_call_logs')
    op.drop_index(op.f('ix_tool_call_logs_tool_name'), table_name='tool_call_logs')
    op.drop_index(op.f('ix_tool_call_logs_created_at'), table_name='tool_call_logs')
    op.drop_index(op.f('ix_tool_call_logs_conversation_id'), table_name='tool_call_logs')
    op.drop_table('tool_call_logs')
    # ### end Alembic commands ###
